### ISSUE TITLE
Not detecting Yamaha rn-602

### ISSUE THREAD

**Issue by calhounfournier** [NorthernMan54/homebridge-yamaha-home#26]
I am trying to connect to my Yamaha r-n602. While the plugin detect the amp it does not recognize it. Technically the procotol should be the same. Any Idea?
<img width="844" alt="screen shot 2019-02-23 at 19 44 55" src="https://user-images.githubusercontent.com/12071592/53293665-15b82800-37a6-11e9-88c7-6f30f4a725b9.png">
<img width="793" alt="screen shot 2019-02-23 at 19 45 13" src="https://user-images.githubusercontent.com/12071592/53293666-15b82800-37a6-11e9-80f3-b9842741afa3.png">

**Comment by NorthernMan54** [comment]
Several hours ago I fixed an issue with the most recent release, how long ago did you install?  Please re-install and try again.

**Comment by calhounfournier** [comment]
I am on the latest release. I uninstalled and reinstalled but it still not work. Maybe the protocol is different protocol. The homebridge-yamaha_mc3 is working, so I can get homebridge to connect.

**Comment by calhounfournier** [comment]
There must be problem with the configuration of my amp. I can't get Yamaha-Nodejs to communicate to simple commands running mocha

**Comment by NorthernMan54** [comment]
Yamaha-NodeJS is scrapping the local web server on the receiver.  Does yours have this? 

![screen shot 2019-02-24 at 8 32 05 am](https://user-images.githubusercontent.com/19808920/53299905-b6dac900-380e-11e9-8ec6-34593bc79cfa.png)

**Comment by calhounfournier** [comment]
No my interface looks more simple. I can get working some parameters found in the attach docuent to work.
[yxc-api-spec-advanced.pdf](https://github.com/NorthernMan54/homebridge-yamaha-home/files/2901775/yxc-api-spec-advanced.pdf)

<img width="802" alt="image" src="https://user-images.githubusercontent.com/12071592/53356375-51173b80-38f9-11e9-97aa-4565e36f8a27.png">

**Comment by NorthernMan54** [comment]
As my plugin is using a different API, I think your stuck.  But I think there may be a different plugin floating around, that is using the musicast interface that this refers to.

**Comment by calhounfournier** [comment]
Thank I'll look into it
